import fs from "node:fs/promises";
import crypto from "node:crypto";
import { envPath } from "./paths.js";

function parseEnvFile(text = "") {
  const values = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const index = line.indexOf("=");
    if (index < 0) continue;
    const key = line.slice(0, index).trim();
    let value = line.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

async function loadLocalEnv() {
  try {
    const env = parseEnvFile(await fs.readFile(envPath, "utf8"));
    for (const [key, value] of Object.entries(env)) {
      if (process.env[key] === undefined) process.env[key] = value;
    }
  } catch {
    // First deployment can start without .env; the setup guide will create it.
  }
}

await loadLocalEnv();

export const config = {
  port: Number(process.env.PORT || 4100),
  nodebbBaseUrl: (process.env.NODEBB_BASE_URL || "http://149.104.21.74:4567").replace(/\/$/, ""),
  nodebbPublicBaseUrl: (process.env.NODEBB_PUBLIC_BASE_URL || process.env.NODEBB_BASE_URL || "http://149.104.21.74:4567").replace(/\/$/, ""),
  nodebbToken: process.env.NODEBB_API_TOKEN || "",
  nodebbUid: Number(process.env.NODEBB_UID || 2),
  nodebbCid: Number(process.env.NODEBB_CID || 2),
  nodebbChannelCid: Number(process.env.NODEBB_CHANNEL_CID || process.env.NODEBB_CID || 2),
  nodebbChannelCidConfigured: Boolean(process.env.NODEBB_CHANNEL_CID),
  nodebbChannelTopicTid: Number(process.env.NODEBB_CHANNEL_TOPIC_TID || 0),
  cloudinaryUrl: process.env.CLOUDINARY_URL || "",
  adminToken: process.env.ADMIN_TOKEN || "",
  mailFrom: process.env.MAIL_FROM || "",
  resendApiKey: process.env.RESEND_API_KEY || "",
  smtpHost: process.env.SMTP_HOST || "",
  smtpPort: Number(process.env.SMTP_PORT || 587),
  smtpUser: process.env.SMTP_USER || "",
  smtpPass: process.env.SMTP_PASS || "",
  smtpSecure: String(process.env.SMTP_SECURE || "").toLowerCase() === "true",
  aiPostPreviewMode: String(process.env.AI_POST_PREVIEW_MODE || "").trim().toLowerCase(),
  mimoApiKey: process.env.MIMO_API_KEY || "",
  mimoBaseUrl: (process.env.MIMO_BASE_URL || "https://api.xiaomimimo.com/v1").replace(/\/$/, ""),
  mimoModel: process.env.MIMO_MODEL || "mimo-v2.5",
  remoteAuthBaseUrl: (process.env.REMOTE_AUTH_BASE_URL || "http://149.104.21.74:4100").replace(/\/$/, "")
};

export function isSetupRequired() {
  return !config.nodebbToken;
}

function quoteEnvValue(value = "") {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export async function saveSetupConfig(payload = {}, onSaved = null) {
  const next = {
    PORT: String(Number(payload.port || config.port || 4100)),
    NODEBB_BASE_URL: String(payload.nodebbBaseUrl || config.nodebbBaseUrl || "").replace(/\/$/, ""),
    NODEBB_PUBLIC_BASE_URL: String(payload.nodebbPublicBaseUrl || config.nodebbPublicBaseUrl || payload.nodebbBaseUrl || config.nodebbBaseUrl || "").replace(/\/$/, ""),
    NODEBB_API_TOKEN: String(payload.nodebbToken || "").trim(),
    NODEBB_UID: String(Number(payload.nodebbUid || config.nodebbUid || 2)),
    NODEBB_CID: String(Number(payload.nodebbCid || config.nodebbCid || 2)),
    CLOUDINARY_URL: String(payload.cloudinaryUrl || config.cloudinaryUrl || "").trim(),
    ADMIN_TOKEN: String(payload.adminToken || config.adminToken || crypto.randomBytes(24).toString("hex")).trim(),
    MAIL_FROM: String(payload.mailFrom || config.mailFrom || "").trim(),
    RESEND_API_KEY: String(payload.resendApiKey || config.resendApiKey || "").trim(),
    SMTP_HOST: String(payload.smtpHost || config.smtpHost || "").trim(),
    SMTP_PORT: String(Number(payload.smtpPort || config.smtpPort || 587)),
    SMTP_USER: String(payload.smtpUser || config.smtpUser || "").trim(),
    SMTP_PASS: String(payload.smtpPass || config.smtpPass || "").trim(),
    SMTP_SECURE: String(payload.smtpSecure ?? config.smtpSecure ?? false)
  };

  if (!next.NODEBB_BASE_URL) throw new Error("NODEBB_BASE_URL is required");
  if (!next.NODEBB_PUBLIC_BASE_URL) throw new Error("NODEBB_PUBLIC_BASE_URL is required");
  if (!next.NODEBB_API_TOKEN) throw new Error("NODEBB_API_TOKEN is required");
  const lines = [
    "# lian-mobile-web local deployment config",
    "# Generated by the first-run setup guide.",
    `PORT=${next.PORT}`,
    `NODEBB_BASE_URL=${quoteEnvValue(next.NODEBB_BASE_URL)}`,
    `NODEBB_PUBLIC_BASE_URL=${quoteEnvValue(next.NODEBB_PUBLIC_BASE_URL)}`,
    `NODEBB_API_TOKEN=${quoteEnvValue(next.NODEBB_API_TOKEN)}`,
    `NODEBB_UID=${next.NODEBB_UID}`,
    `NODEBB_CID=${next.NODEBB_CID}`,
    `CLOUDINARY_URL=${quoteEnvValue(next.CLOUDINARY_URL)}`,
    `ADMIN_TOKEN=${quoteEnvValue(next.ADMIN_TOKEN)}`,
    `MAIL_FROM=${quoteEnvValue(next.MAIL_FROM)}`,
    `RESEND_API_KEY=${quoteEnvValue(next.RESEND_API_KEY)}`,
    `SMTP_HOST=${quoteEnvValue(next.SMTP_HOST)}`,
    `SMTP_PORT=${next.SMTP_PORT}`,
    `SMTP_USER=${quoteEnvValue(next.SMTP_USER)}`,
    `SMTP_PASS=${quoteEnvValue(next.SMTP_PASS)}`,
    `SMTP_SECURE=${next.SMTP_SECURE}`
  ];
  await fs.writeFile(envPath, `${lines.join("\n")}\n`, "utf8");

  config.port = Number(next.PORT);
  config.nodebbBaseUrl = next.NODEBB_BASE_URL;
  config.nodebbPublicBaseUrl = next.NODEBB_PUBLIC_BASE_URL;
  config.nodebbToken = next.NODEBB_API_TOKEN;
  config.nodebbUid = Number(next.NODEBB_UID);
  config.nodebbCid = Number(next.NODEBB_CID);
  config.cloudinaryUrl = next.CLOUDINARY_URL;
  config.adminToken = next.ADMIN_TOKEN;
  config.mailFrom = next.MAIL_FROM;
  config.resendApiKey = next.RESEND_API_KEY;
  config.smtpHost = next.SMTP_HOST;
  config.smtpPort = Number(next.SMTP_PORT);
  config.smtpUser = next.SMTP_USER;
  config.smtpPass = next.SMTP_PASS;
  config.smtpSecure = String(next.SMTP_SECURE).toLowerCase() === "true";
  onSaved?.();
}
