import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.join(__dirname, "public");
const rulesPath = path.join(__dirname, "data", "feed-rules.json");
const metadataPath = path.join(__dirname, "data", "post-metadata.json");
const snapshotPath = path.join(__dirname, "data", "nodebb-snapshot.json");
const snapshotAssetDir = path.join(publicDir, "snapshot-assets");
const envPath = path.join(__dirname, ".env");

function parseEnvFile(text = "") {
  const values = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const index = line.indexOf("=");
    if (index < 0) continue;
    const key = line.slice(0, index).trim();
    let value = line.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

async function loadLocalEnv() {
  try {
    const env = parseEnvFile(await fs.readFile(envPath, "utf8"));
    for (const [key, value] of Object.entries(env)) {
      if (process.env[key] === undefined) process.env[key] = value;
    }
  } catch {
    // First deployment can start without .env; the setup guide will create it.
  }
}

await loadLocalEnv();

const config = {
  port: Number(process.env.PORT || 4100),
  nodebbBaseUrl: (process.env.NODEBB_BASE_URL || "http://149.104.21.74:4567").replace(/\/$/, ""),
  nodebbToken: process.env.NODEBB_API_TOKEN || "",
  nodebbUid: Number(process.env.NODEBB_UID || 2),
  nodebbCid: Number(process.env.NODEBB_CID || 2),
  cloudinaryUrl: process.env.CLOUDINARY_URL || "",
  adminToken: process.env.ADMIN_TOKEN || "",
  dataMode: (process.env.DATA_MODE || "live").toLowerCase(),
  snapshotRetryAttempts: Number(process.env.SNAPSHOT_RETRY_ATTEMPTS || 3)
};

function isSetupRequired() {
  return !config.nodebbToken;
}

function quoteEnvValue(value = "") {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

async function saveSetupConfig(payload = {}) {
  const next = {
    PORT: String(Number(payload.port || config.port || 4100)),
    NODEBB_BASE_URL: String(payload.nodebbBaseUrl || config.nodebbBaseUrl || "").replace(/\/$/, ""),
    NODEBB_API_TOKEN: String(payload.nodebbToken || "").trim(),
    NODEBB_UID: String(Number(payload.nodebbUid || config.nodebbUid || 2)),
    NODEBB_CID: String(Number(payload.nodebbCid || config.nodebbCid || 2)),
    DATA_MODE: String(payload.dataMode || config.dataMode || "snapshot").toLowerCase(),
    SNAPSHOT_RETRY_ATTEMPTS: String(Number(payload.snapshotRetryAttempts || config.snapshotRetryAttempts || 3)),
    CLOUDINARY_URL: String(payload.cloudinaryUrl || config.cloudinaryUrl || "").trim(),
    ADMIN_TOKEN: String(payload.adminToken || config.adminToken || crypto.randomBytes(24).toString("hex")).trim()
  };

  if (!next.NODEBB_BASE_URL) throw new Error("NODEBB_BASE_URL is required");
  if (!next.NODEBB_API_TOKEN) throw new Error("NODEBB_API_TOKEN is required");
  if (!["live", "snapshot"].includes(next.DATA_MODE)) throw new Error("DATA_MODE must be live or snapshot");

  const lines = [
    "# lian-mobile-web local deployment config",
    "# Generated by the first-run setup guide.",
    `PORT=${next.PORT}`,
    `NODEBB_BASE_URL=${quoteEnvValue(next.NODEBB_BASE_URL)}`,
    `NODEBB_API_TOKEN=${quoteEnvValue(next.NODEBB_API_TOKEN)}`,
    `NODEBB_UID=${next.NODEBB_UID}`,
    `NODEBB_CID=${next.NODEBB_CID}`,
    `DATA_MODE=${next.DATA_MODE}`,
    `SNAPSHOT_RETRY_ATTEMPTS=${next.SNAPSHOT_RETRY_ATTEMPTS}`,
    `CLOUDINARY_URL=${quoteEnvValue(next.CLOUDINARY_URL)}`,
    `ADMIN_TOKEN=${quoteEnvValue(next.ADMIN_TOKEN)}`
  ];
  await fs.writeFile(envPath, `${lines.join("\n")}\n`, "utf8");

  config.port = Number(next.PORT);
  config.nodebbBaseUrl = next.NODEBB_BASE_URL;
  config.nodebbToken = next.NODEBB_API_TOKEN;
  config.nodebbUid = Number(next.NODEBB_UID);
  config.nodebbCid = Number(next.NODEBB_CID);
  config.dataMode = next.DATA_MODE;
  config.snapshotRetryAttempts = Number(next.SNAPSHOT_RETRY_ATTEMPTS);
  config.cloudinaryUrl = next.CLOUDINARY_URL;
  config.adminToken = next.ADMIN_TOKEN;
  memory.feedPages.clear();
  memory.topicDetails.clear();
}

const memory = {
  topicDetails: new Map(),
  feedPages: new Map(),
  rules: null,
  rulesLoadedAt: 0,
  metadata: null,
  metadataLoadedAt: 0,
  snapshot: null,
  snapshotLoadedAt: 0,
  snapshotSyncPromise: null
};

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp"
};

const mapItems = [
  { id: "teaching", title: "公共教学楼", type: "place", lat: 18.400032, lng: 110.016989 },
  { id: "lab", title: "公共实验楼", type: "place", lat: 18.401458, lng: 110.018094 },
  { id: "canteen-1", title: "一号食堂", type: "food", lat: 18.401799, lng: 110.020122 },
  { id: "library", title: "图书馆", type: "study", lat: 18.403036, lng: 110.014774 },
  { id: "gym", title: "综合体育馆", type: "sport", lat: 18.404374, lng: 110.02143 },
  { id: "dorm-1", title: "生活一区", type: "life", lat: 18.395955, lng: 110.016671 },
  { id: "dorm-2", title: "生活二区", type: "life", lat: 18.397625, lng: 110.018474 },
  { id: "hall", title: "学生会堂", type: "place", lat: 18.39596, lng: 110.014161 },
  { id: "bsu", title: "北京体育大学专享楼", type: "school", lat: 18.403964, lng: 110.018973 },
  { id: "cuc", title: "中国传媒大学专享楼", type: "school", lat: 18.399433, lng: 110.013919 }
];

function sendJson(res, status, body) {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "no-store"
  });
  res.end(payload);
}

function sendText(res, status, text, type = "text/plain; charset=utf-8") {
  res.writeHead(status, { "content-type": type });
  res.end(text);
}

function setupPageHtml() {
  return `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <title>黎安信息流部署引导</title>
    <style>
      :root { color-scheme: light; --bg:#f7f7f4; --paper:#fff; --ink:#1d2320; --muted:#69706b; --line:#e7e3da; --green:#157f5b; --red:#d95745; }
      * { box-sizing: border-box; }
      body { margin:0; min-height:100vh; background:var(--bg); color:var(--ink); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif; }
      main { width:min(100% - 28px, 640px); margin:0 auto; padding:34px 0 48px; }
      h1 { margin:0; font-size:28px; line-height:1.2; letter-spacing:0; }
      p { color:var(--muted); line-height:1.7; }
      form { margin-top:22px; padding:18px; border:1px solid var(--line); border-radius:8px; background:var(--paper); box-shadow:0 8px 24px rgba(29,35,32,.07); }
      label { display:grid; gap:7px; margin-bottom:14px; font-size:13px; font-weight:700; color:#424b46; }
      input, select { width:100%; border:1px solid var(--line); border-radius:8px; background:#fbfaf7; color:var(--ink); padding:11px 12px; outline:none; font:inherit; }
      button { width:100%; min-height:46px; border:0; border-radius:8px; background:var(--ink); color:#fff; font:inherit; font-weight:800; }
      code { padding:2px 5px; border-radius:5px; background:#eeeae1; }
      .grid { display:grid; grid-template-columns:1fr 1fr; gap:12px; }
      .hint { margin:8px 0 0; font-size:12px; color:var(--muted); }
      .status { min-height:22px; margin-top:12px; font-size:13px; color:var(--red); }
      .status.ok { color:var(--green); }
      @media (max-width:560px) { .grid { grid-template-columns:1fr; } main { padding-top:24px; } }
    </style>
  </head>
  <body>
    <main>
      <h1>部署引导</h1>
      <p>这是第一次启动，服务还没有 NodeBB 连接配置。保存后会在服务器目录生成 <code>.env</code>，刷新页面即可进入信息流。</p>
      <form id="setupForm">
        <label>NodeBB 地址
          <input name="nodebbBaseUrl" required value="http://127.0.0.1:4567" placeholder="http://127.0.0.1:4567">
          <span class="hint">Linux Web 服务和 NodeBB 在同一台服务器时，建议用 127.0.0.1。</span>
        </label>
        <label>NodeBB API Token
          <input name="nodebbToken" required autocomplete="off" placeholder="Bearer token 或 NodeBB API token">
        </label>
        <div class="grid">
          <label>发帖用户 UID
            <input name="nodebbUid" type="number" min="1" value="2">
          </label>
          <label>默认分类 CID
            <input name="nodebbCid" type="number" min="1" value="2">
          </label>
        </div>
        <div class="grid">
          <label>Web 端口
            <input name="port" type="number" min="1" max="65535" value="4100">
          </label>
          <label>数据模式
            <select name="dataMode">
              <option value="snapshot" selected>snapshot：优先同步，失败读本地快照</option>
              <option value="live">live：只读 NodeBB API</option>
            </select>
          </label>
        </div>
        <label>Cloudinary URL
          <input name="cloudinaryUrl" autocomplete="off" placeholder="cloudinary://api_key:api_secret@cloud_name">
          <span class="hint">需要在网页里上传图片发帖时填写；只浏览可以先留空。</span>
        </label>
        <label>管理接口 Token
          <input name="adminToken" autocomplete="off" placeholder="留空会自动生成">
          <span class="hint">用于远程更新推荐规则和帖子时效信息，请不要公开。</span>
        </label>
        <button type="submit">保存配置并进入</button>
        <div class="status" id="status"></div>
      </form>
    </main>
    <script>
      const form = document.getElementById("setupForm");
      const status = document.getElementById("status");
      form.addEventListener("submit", async (event) => {
        event.preventDefault();
        status.className = "status";
        status.textContent = "正在保存...";
        const payload = Object.fromEntries(new FormData(form).entries());
        const response = await fetch("/api/setup", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify(payload)
        });
        const data = await response.json().catch(() => ({}));
        if (!response.ok) {
          status.textContent = data.error || "保存失败";
          return;
        }
        status.className = "status ok";
        status.textContent = "已保存，正在进入...";
        setTimeout(() => location.replace("/"), 500);
      });
    </script>
  </body>
</html>`;
}

function addUid(url) {
  if (url.searchParams.has("_uid")) return url;
  url.searchParams.set("_uid", String(config.nodebbUid));
  return url;
}

async function nodebbFetch(apiPath, options = {}) {
  const url = addUid(new URL(apiPath, config.nodebbBaseUrl));
  const headers = {
    accept: "application/json",
    connection: "close",
    ...options.headers
  };
  if (config.nodebbToken && !headers.authorization) {
    headers["x-api-token"] = config.nodebbToken;
  }

  let response;
  try {
    response = await fetch(url, { ...options, headers });
  } catch (cause) {
    const error = new Error(`NodeBB API connection failed: ${url.origin}${url.pathname} - ${cause.message || cause}`);
    error.status = 502;
    error.cause = cause;
    throw error;
  }
  const text = await response.text();
  let data = null;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = { raw: text };
    }
  }

  if (!response.ok) {
    const message = data?.error || data?.message || text || `NodeBB HTTP ${response.status}`;
    const error = new Error(message);
    error.status = response.status;
    error.data = data;
    throw error;
  }

  return data;
}

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function retryApi(task, attempts = config.snapshotRetryAttempts) {
  let lastError;
  for (let index = 0; index < Math.max(1, attempts); index += 1) {
    try {
      return await task();
    } catch (error) {
      lastError = error;
      if (index < attempts - 1) await delay(450 * (index + 1));
    }
  }
  throw lastError;
}

function snapshotSignature(topics = []) {
  return topics
    .map((topic) => [
      topic.tid,
      topic.titleRaw || topic.title || "",
      topic.timestamp || "",
      topic.lastposttime || "",
      topic.postcount || 0,
      topic.deleted || 0
    ].join(":"))
    .sort()
    .join("|");
}

async function readSnapshot() {
  const now = Date.now();
  if (memory.snapshot && now - memory.snapshotLoadedAt < 10_000) return memory.snapshot;
  const raw = await fs.readFile(snapshotPath, "utf8");
  memory.snapshot = JSON.parse(raw);
  memory.snapshotLoadedAt = now;
  return memory.snapshot;
}

async function writeSnapshot(data) {
  await fs.mkdir(path.dirname(snapshotPath), { recursive: true });
  const tmpPath = `${snapshotPath}.tmp`;
  await fs.writeFile(tmpPath, JSON.stringify(data, null, 2), "utf8");
  await fs.rename(tmpPath, snapshotPath);
  memory.snapshot = data;
  memory.snapshotLoadedAt = Date.now();
}

async function writeJsonFile(filePath, data) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const tmpPath = `${filePath}.tmp`;
  await fs.writeFile(tmpPath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
  await fs.rename(tmpPath, filePath);
}

async function downloadSnapshotAsset(url) {
  if (!/^https?:\/\//i.test(url)) return url;
  await fs.mkdir(snapshotAssetDir, { recursive: true });
  const parsed = new URL(url);
  const extFromPath = path.extname(parsed.pathname).toLowerCase();
  const ext = [".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"].includes(extFromPath) ? extFromPath : ".jpg";
  const name = `${crypto.createHash("sha1").update(url).digest("hex")}${ext}`;
  const filePath = path.join(snapshotAssetDir, name);
  const publicUrl = `/snapshot-assets/${name}`;
  try {
    await fs.access(filePath);
    return publicUrl;
  } catch {
    // continue and download
  }

  const response = await retryApi(() => fetch(url, { headers: { connection: "close" } }), 2);
  if (!response.ok) return url;
  const bytes = Buffer.from(await response.arrayBuffer());
  await fs.writeFile(filePath, bytes);
  return publicUrl;
}

async function localizeHtmlImages(html = "") {
  const matches = Array.from(html.matchAll(/<img[^>]+src=["']([^"']+)["'][^>]*>/gi));
  let localized = html;
  for (const match of matches) {
    const originalUrl = match[1].replace(/&amp;/g, "&");
    const localUrl = await downloadSnapshotAsset(originalUrl);
    localized = localized.split(match[1]).join(localUrl);
  }
  return localized;
}

async function fetchNodebbTopicIndex(maxPages = 8) {
  const pages = [];
  for (let page = 1; page <= maxPages; page += 1) {
    const data = await retryApi(() => nodebbFetch(`/api/recent?page=${page}`));
    const topics = Array.isArray(data?.topics) ? data.topics : [];
    if (!topics.length) break;
    pages.push(data);
  }

  const seen = new Set();
  const topics = [];
  for (const page of pages) {
    for (const topic of page.topics || []) {
      if (!topic?.tid || seen.has(topic.tid)) continue;
      seen.add(topic.tid);
      topics.push(topic);
    }
  }
  return topics;
}

async function fetchNodebbSnapshot(existingSnapshot = null) {
  const topics = await fetchNodebbTopicIndex();
  const signature = snapshotSignature(topics);
  if (existingSnapshot?.signature === signature) {
    return {
      ...existingSnapshot,
      checkedAt: new Date().toISOString(),
      source: "api-unchanged"
    };
  }

  const details = {};
  for (const topic of topics) {
    const detail = await retryApi(() => nodebbFetch(`/api/topic/${topic.tid}`));
    if (detail?.posts?.[0]?.content) {
      detail.posts[0].content = await localizeHtmlImages(detail.posts[0].content);
    }
    details[String(topic.tid)] = detail;
  }

  return {
    version: 1,
    source: "api-updated",
    sourceBaseUrl: config.nodebbBaseUrl,
    generatedAt: new Date().toISOString(),
    checkedAt: new Date().toISOString(),
    signature,
    topics,
    details
  };
}

async function getSnapshotData() {
  let existing = null;
  try {
    existing = await readSnapshot();
  } catch {
    existing = null;
  }

  if (!memory.snapshotSyncPromise) {
    memory.snapshotSyncPromise = fetchNodebbSnapshot(existing)
      .then(async (snapshot) => {
        if (!existing || snapshot.signature !== existing.signature || snapshot.source === "api-updated") {
          await writeSnapshot(snapshot);
        } else {
          memory.snapshot = snapshot;
          memory.snapshotLoadedAt = Date.now();
        }
        return snapshot;
      })
      .finally(() => {
        memory.snapshotSyncPromise = null;
      });
  }

  try {
    return await memory.snapshotSyncPromise;
  } catch (apiError) {
    if (existing) {
      return {
        ...existing,
        source: "snapshot",
        apiError: apiError.message || String(apiError)
      };
    }
    throw apiError;
  }
}

async function loadRules() {
  const now = Date.now();
  if (memory.rules && now - memory.rulesLoadedAt < 15_000) return memory.rules;
  try {
    const raw = await fs.readFile(rulesPath, "utf8");
    memory.rules = JSON.parse(raw);
  } catch {
    memory.rules = { tabs: ["推荐"], pinnedTids: [], tagWeights: {}, recencyHalfLifeHours: 96, coverBonus: 0 };
  }
  memory.rulesLoadedAt = now;
  return memory.rules;
}

async function loadMetadata() {
  const now = Date.now();
  if (memory.metadata && now - memory.metadataLoadedAt < 15_000) return memory.metadata;
  try {
    const raw = await fs.readFile(metadataPath, "utf8");
    const data = JSON.parse(raw);
    memory.metadata = data.items || {};
  } catch {
    memory.metadata = {};
  }
  memory.metadataLoadedAt = now;
  return memory.metadata;
}

function stripHtml(html = "") {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/&#39;/g, "'")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function extractCover(html = "") {
  const img = html.match(/<img[^>]+src=["']([^"']+)["']/i);
  if (img?.[1]) return img[1].replace(/&amp;/g, "&");
  const md = html.match(/!\[[^\]]*]\((https?:\/\/[^)\s]+)\)/i);
  return md?.[1] || "";
}

function extractSourceUrl(html = "") {
  const linked = html.match(/href=["'](https?:\/\/mp\.weixin\.qq\.com\/[^"']+)["']/i);
  if (linked?.[1]) return linked[1].replace(/&amp;/g, "&");
  const text = stripHtml(html);
  const original = text.match(/原文[:：]\s*(https?:\/\/\S+)/);
  if (original?.[1]) return original[1];
  const anyWechat = text.match(/https?:\/\/mp\.weixin\.qq\.com\/\S+/);
  return anyWechat?.[0] || "";
}

function removeOriginalLinkBlocks(html = "") {
  return html
    .replace(/<p>\s*\?{2,}\s*<a[^>]+href=["']https?:\/\/mp\.weixin\.qq\.com\/[^"']+["'][\s\S]*?<\/a>\s*<\/p>/gi, "")
    .replace(/<p>\s*原文[:：]\s*<a[^>]+href=["']https?:\/\/mp\.weixin\.qq\.com\/[^"']+["'][\s\S]*?<\/a>\s*<\/p>/gi, "")
    .replace(/<p>\s*原文[:：]\s*https?:\/\/mp\.weixin\.qq\.com\/[^<\s]+?\s*<\/p>/gi, "")
    .trim();
}

function extractSummary(html = "", title = "") {
  const lines = stripHtml(html)
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => !line.startsWith("#"))
    .filter((line) => !/^原文[:：]/.test(line))
    .filter((line) => !/^信息来自/.test(line))
    .filter((line) => line !== title);

  const summary = lines.join(" ").replace(/\s+/g, " ").trim();
  if (!summary) return "点开看看详情。";
  return summary.length > 92 ? `${summary.slice(0, 92)}...` : summary;
}

function normalizeTopic(topic, detail = null, metadata = {}) {
  const firstPost = detail?.posts?.[0] || {};
  const contentHtml = firstPost.content || topic?.teaser?.content || "";
  const tags = Array.isArray(detail?.tags) && detail.tags.length ? detail.tags : topic?.tags || [];
  const tag = tags[0]?.value || tags[0]?.name || "";
  const timestampISO = detail?.timestampISO || topic?.timestampISO || firstPost.timestampISO || "";
  const title = detail?.titleRaw || detail?.title || topic?.titleRaw || topic?.title || "未命名";
  const tid = detail?.tid || topic?.tid;
  const meta = metadata[String(tid)] || {};

  return {
    id: String(tid),
    tid,
    title,
    tag,
    tags: tags.map((item) => item.value || item.name || item).filter(Boolean),
    summary: extractSummary(contentHtml, title),
    cover: extractCover(contentHtml),
    timestampISO,
    timeLabel: meta.timeLabel || "",
    startsAt: meta.startsAt || null,
    endsAt: meta.endsAt || null,
    expiresAt: meta.expiresAt || null,
    priority: Number(meta.priority || 0),
    isExpired: Boolean(meta.expiresAt && Date.now() > Date.parse(meta.expiresAt)),
    author: firstPost?.user?.username || topic?.user?.username || "猴岛情报站",
    replyCount: detail?.postcount ? Math.max(0, detail.postcount - 1) : topic?.postcount || 0,
    nodebbUrl: `${config.nodebbBaseUrl}/topic/${tid}`,
    sourceUrl: extractSourceUrl(contentHtml)
  };
}

async function getTopicDetail(tid) {
  const cached = memory.topicDetails.get(tid);
  if (cached && Date.now() - cached.at < 180_000) return cached.data;
  const data = await nodebbFetch(`/api/topic/${tid}`);
  memory.topicDetails.set(tid, { at: Date.now(), data });
  return data;
}

async function getRecentTopics(page = 1) {
  const key = String(page);
  const cached = memory.feedPages.get(key);
  if (cached && Date.now() - cached.at < 60_000) return cached.data;
  const data = await nodebbFetch(`/api/recent?page=${page}`);
  memory.feedPages.set(key, { at: Date.now(), data });
  return data;
}

async function getAllRecentTopics(maxPages = 6) {
  const pages = await Promise.all(
    Array.from({ length: maxPages }, (_, index) => getRecentTopics(index + 1))
  );
  const seen = new Set();
  const topics = [];
  for (const page of pages) {
    for (const topic of page?.topics || []) {
      if (!topic?.tid || seen.has(topic.tid)) continue;
      seen.add(topic.tid);
      topics.push(topic);
    }
  }
  return topics;
}

function scoreItem(item, rules) {
  if (item.isExpired) return -10_000;
  const pinnedIndex = (rules.pinnedTids || []).indexOf(Number(item.tid));
  const pinned = pinnedIndex >= 0 ? 1000 - pinnedIndex * 5 : 0;
  const tagWeight = rules.tagWeights?.[item.tag] || 0;
  const activeTime = item.startsAt || item.endsAt || item.expiresAt || item.timestampISO || new Date().toISOString();
  const ageMs = Math.abs(Date.now() - Date.parse(activeTime));
  const halfLife = Math.max(1, Number(rules.recencyHalfLifeHours || 96));
  const recency = 60 * Math.pow(0.5, ageMs / (halfLife * 3600_000));
  const cover = item.cover ? Number(rules.coverBonus || 0) : 0;
  return pinned + tagWeight + recency + cover + item.priority;
}

function getCuratedPages(rules) {
  const pages = rules?.feedEditions?.pages;
  if (!Array.isArray(pages)) return [];
  return pages
    .map((page) => (Array.isArray(page) ? page : page?.tids))
    .filter(Array.isArray)
    .map((page) => page.map(Number).filter(Number.isFinite))
    .filter((page) => page.length);
}

function chunkItems(items, size) {
  const chunks = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

function personalizeBatch(items, readTids) {
  return [...items].sort((a, b) => {
    const aRead = readTids.has(Number(a.tid)) ? 1 : 0;
    const bRead = readTids.has(Number(b.tid)) ? 1 : 0;
    if (aRead !== bRead) return aRead - bRead;
    return 0;
  });
}

function parseReadTids(value = "") {
  return new Set(
    String(value)
      .split(",")
      .map((item) => Number(item.trim()))
      .filter(Number.isFinite)
  );
}

async function handleFeed(reqUrl, res) {
  const rules = await loadRules();
  const metadata = await loadMetadata();
  const tab = reqUrl.searchParams.get("tab") || "推荐";
  const page = Math.max(1, Number(reqUrl.searchParams.get("page") || 1));
  const editionPageSize = Number(rules?.feedEditions?.pageSize || 10);
  const limit = Math.min(24, Math.max(4, Number(reqUrl.searchParams.get("limit") || editionPageSize || 10)));
  const readTids = parseReadTids(reqUrl.searchParams.get("read") || "");
  const snapshot = config.dataMode === "snapshot" ? await getSnapshotData() : null;
  const topics = snapshot ? snapshot.topics || [] : await getAllRecentTopics();
  const basicItems = topics.map((topic) => normalizeTopic(topic, null, metadata));
  const itemByTid = new Map(basicItems.map((item) => [Number(item.tid), item]));

  let items = basicItems;
  let selected;
  let hasMore;
  const curatedPages = tab === "推荐" ? getCuratedPages(rules) : [];
  if (tab !== "推荐") {
    items = items.filter((item) => item.tags.includes(tab) || item.tag === tab);
    const start = (page - 1) * limit;
    selected = items.slice(start, start + limit);
    hasMore = start + selected.length < items.length;
  } else if (curatedPages.length) {
    const used = new Set();
    const pages = curatedPages.map((tids) => {
      const pageItems = tids
        .map((tid) => itemByTid.get(Number(tid)))
        .filter(Boolean);
      pageItems.forEach((item) => used.add(Number(item.tid)));
      return pageItems;
    });
    const rankedRest = basicItems
      .filter((item) => !used.has(Number(item.tid)))
      .sort((a, b) => scoreItem(b, rules) - scoreItem(a, rules));
    const restPages = chunkItems(rankedRest, Math.max(4, editionPageSize || limit));
    const allPages = [...pages, ...restPages].filter((batch) => batch.length);
    selected = personalizeBatch(allPages[page - 1] || [], readTids);
    hasMore = page < allPages.length;
  } else {
    items = items.sort((a, b) => scoreItem(b, rules) - scoreItem(a, rules));
    const start = (page - 1) * limit;
    selected = personalizeBatch(items.slice(start, start + limit), readTids);
    hasMore = start + selected.length < items.length;
  }

  const sliced = await Promise.all(
    selected.map(async (item) => {
      const topic = topics.find((candidate) => candidate.tid === item.tid) || item;
      try {
        const detail = snapshot ? snapshot.details?.[String(item.tid)] : await getTopicDetail(item.tid);
        return normalizeTopic(topic, detail, metadata);
      } catch {
        return item;
      }
    })
  );
  sendJson(res, 200, {
    items: sliced,
    page,
    nextPage: hasMore ? page + 1 : null,
    hasMore,
    tabs: rules.tabs || ["推荐"],
    feedEdition: curatedPages.length ? {
      mode: "curated",
      pageSize: editionPageSize,
      generatedAt: rules.feedEditions?.generatedAt || null,
      pageNote: rules.feedEditions?.notes?.[page - 1] || ""
    } : { mode: "scored" },
    dataMode: config.dataMode,
    dataSource: snapshot?.source || "api",
    apiError: snapshot?.apiError || null,
    snapshotCheckedAt: snapshot?.checkedAt || null
  });
}

async function handlePostDetail(tid, res) {
  const metadata = await loadMetadata();
  const snapshot = config.dataMode === "snapshot" ? await getSnapshotData() : null;
  const detail = snapshot ? snapshot.details?.[String(tid)] : await getTopicDetail(tid);
  if (!detail) {
    sendJson(res, 404, { error: "topic not found in snapshot" });
    return;
  }
  const firstPost = detail?.posts?.[0] || {};
  const sourceUrl = extractSourceUrl(firstPost.content || "");
  sendJson(res, 200, {
    ...normalizeTopic({ tid }, detail, metadata),
    sourceUrl,
    contentHtml: removeOriginalLinkBlocks(firstPost.content || ""),
    dataMode: config.dataMode,
    dataSource: snapshot?.source || "api",
    raw: {
      tid: detail.tid,
      slug: detail.slug,
      timestampISO: detail.timestampISO,
      tags: detail.tags || []
    }
  });
}

async function readJsonBody(req) {
  let body = "";
  for await (const chunk of req) body += chunk;
  if (!body.trim()) return {};
  return JSON.parse(body);
}

function getAuthToken(req) {
  const header = req.headers.authorization || "";
  const bearer = header.match(/^Bearer\s+(.+)$/i)?.[1];
  return bearer || req.headers["x-admin-token"] || "";
}

function requireAdmin(req) {
  if (!config.adminToken) {
    const error = new Error("ADMIN_TOKEN is missing");
    error.status = 503;
    throw error;
  }
  if (getAuthToken(req) !== config.adminToken) {
    const error = new Error("admin authorization failed");
    error.status = 401;
    throw error;
  }
}

async function readBodyBuffer(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(Buffer.from(chunk));
  return Buffer.concat(chunks);
}

function parseMultipart(buffer, contentType = "") {
  const boundaryMatch = contentType.match(/boundary=(?:"([^"]+)"|([^;]+))/i);
  if (!boundaryMatch) throw new Error("Missing multipart boundary");
  const boundary = Buffer.from(`--${boundaryMatch[1] || boundaryMatch[2]}`);
  const parts = [];
  let cursor = buffer.indexOf(boundary);

  while (cursor >= 0) {
    let start = cursor + boundary.length;
    if (buffer[start] === 45 && buffer[start + 1] === 45) break;
    if (buffer[start] === 13 && buffer[start + 1] === 10) start += 2;

    const next = buffer.indexOf(boundary, start);
    if (next < 0) break;

    let end = next;
    if (buffer[end - 2] === 13 && buffer[end - 1] === 10) end -= 2;
    const part = buffer.subarray(start, end);
    const headerEnd = part.indexOf(Buffer.from("\r\n\r\n"));
    if (headerEnd > 0) {
      const rawHeaders = part.subarray(0, headerEnd).toString("utf8");
      const body = part.subarray(headerEnd + 4);
      const name = rawHeaders.match(/name="([^"]+)"/)?.[1] || "";
      const filename = rawHeaders.match(/filename="([^"]*)"/)?.[1] || "";
      const type = rawHeaders.match(/content-type:\s*([^\r\n]+)/i)?.[1] || "application/octet-stream";
      parts.push({ name, filename, type, body });
    }

    cursor = next;
  }

  return parts;
}

async function getCloudinaryUrl() {
  if (config.cloudinaryUrl) return config.cloudinaryUrl;
  const localEnv = path.resolve(__dirname, "../NodeBB-frontend/.env.local");
  try {
    const text = await fs.readFile(localEnv, "utf8");
    const line = text.split(/\r?\n/).find((item) => item.startsWith("CLOUDINARY_URL="));
    if (line) return line.slice("CLOUDINARY_URL=".length).trim();
  } catch {
    return "";
  }
  return "";
}

async function uploadImageToCloudinary(file) {
  const cloudinaryUrl = await getCloudinaryUrl();
  if (!cloudinaryUrl) throw new Error("CLOUDINARY_URL is missing");

  const uri = new URL(cloudinaryUrl);
  const [apiKey, apiSecret] = decodeURIComponent(uri.username + ":" + uri.password).split(":");
  const cloudName = uri.hostname;
  const folder = "nodebb-frontend/mobile-web-upload";
  const timestamp = Math.floor(Date.now() / 1000);
  const signature = crypto
    .createHash("sha1")
    .update(`folder=${folder}&timestamp=${timestamp}${apiSecret}`)
    .digest("hex");

  const form = new FormData();
  form.append("file", new Blob([file.body], { type: file.type }), file.filename || "upload.jpg");
  form.append("api_key", apiKey);
  form.append("timestamp", String(timestamp));
  form.append("signature", signature);
  form.append("folder", folder);

  const response = await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`, {
    method: "POST",
    body: form
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok || !data.secure_url) {
    throw new Error(data?.error?.message || "Cloudinary upload failed");
  }
  return data.secure_url;
}

async function handleUploadImage(req, res) {
  const buffer = await readBodyBuffer(req);
  const parts = parseMultipart(buffer, req.headers["content-type"] || "");
  const file = parts.find((part) => part.name === "image" && part.filename && part.body.length);
  if (!file) {
    sendJson(res, 400, { error: "image file is required" });
    return;
  }
  if (!file.type.startsWith("image/")) {
    sendJson(res, 400, { error: "only image files are supported" });
    return;
  }
  const url = await uploadImageToCloudinary(file);
  sendJson(res, 200, { url });
}

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildTopicHtml(payload) {
  const blocks = [];
  if (payload.imageUrl) {
    blocks.push(`<img src="${escapeHtml(payload.imageUrl)}" alt="${escapeHtml(payload.title || "cover")}" style="max-width:100%;height:auto" />`);
  }
  if (payload.tag) blocks.push(`<p><strong>#${escapeHtml(payload.tag)}</strong></p>`);
  const content = String(payload.content || "")
    .split(/\n{2,}/)
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => `<p>${escapeHtml(part).replace(/\n/g, "<br>")}</p>`);
  blocks.push(...content);
  if (payload.placeName || (payload.lat && payload.lng)) {
    const place = [payload.placeName, payload.lat && payload.lng ? `${payload.lat}, ${payload.lng}` : ""].filter(Boolean).join(" ");
    blocks.push(`<p>地点：${escapeHtml(place)}</p>`);
  }
  return blocks.join("\n\n").trim();
}

async function handleCreatePost(req, res) {
  if (!config.nodebbToken) {
    sendJson(res, 500, { error: "NODEBB_API_TOKEN is missing" });
    return;
  }
  const payload = await readJsonBody(req);
  const title = String(payload.title || "").trim();
  if (!title) {
    sendJson(res, 400, { error: "title is required" });
    return;
  }
  const content = buildTopicHtml(payload);
  const body = {
    cid: Number(payload.cid || config.nodebbCid),
    title,
    content,
    tags: payload.tag ? [payload.tag] : undefined
  };
  const data = await nodebbFetch("/api/v3/topics", {
    method: "POST",
    headers: {
      "content-type": "application/json; charset=utf-8",
      authorization: `Bearer ${config.nodebbToken}`
    },
    body: JSON.stringify(body)
  });
  memory.feedPages.clear();
  sendJson(res, 200, data);
}

async function handleMessages(res) {
  try {
    const data = await nodebbFetch("/api/notifications");
    const items = (data?.notifications || []).slice(0, 30).map((item) => ({
      id: item.nid || item.datetime || item.path,
      title: stripHtml(item.bodyShort || item.bodyLong || item.text || "新消息"),
      time: item.datetimeISO || item.datetime || "",
      url: item.path ? `${config.nodebbBaseUrl}${item.path}` : config.nodebbBaseUrl
    }));
    sendJson(res, 200, { items });
  } catch {
    sendJson(res, 200, { items: [] });
  }
}

async function handleMe(res) {
  try {
    const data = await nodebbFetch(`/api/user/uid/${config.nodebbUid}`);
    sendJson(res, 200, {
      uid: data?.uid || config.nodebbUid,
      username: data?.username || "猴岛情报站",
      picture: data?.picture || "",
      reputation: data?.reputation || 0,
      postcount: data?.postcount || 0,
      topiccount: data?.topiccount || 0
    });
  } catch {
    sendJson(res, 200, { uid: config.nodebbUid, username: "猴岛情报站", picture: "", reputation: 0, postcount: 0, topiccount: 0 });
  }
}

async function handleAdmin(req, reqUrl, res) {
  requireAdmin(req);

  if (req.method === "GET" && reqUrl.pathname === "/api/admin/feed-rules") {
    const raw = await fs.readFile(rulesPath, "utf8");
    return sendJson(res, 200, JSON.parse(raw));
  }

  if (req.method === "PUT" && reqUrl.pathname === "/api/admin/feed-rules") {
    const payload = await readJsonBody(req);
    if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
      return sendJson(res, 400, { error: "feed rules must be a JSON object" });
    }
    if (payload.tabs && !Array.isArray(payload.tabs)) {
      return sendJson(res, 400, { error: "tabs must be an array" });
    }
    if (payload.pinnedTids && !Array.isArray(payload.pinnedTids)) {
      return sendJson(res, 400, { error: "pinnedTids must be an array" });
    }
    await writeJsonFile(rulesPath, payload);
    memory.rules = payload;
    memory.rulesLoadedAt = Date.now();
    memory.feedPages.clear();
    return sendJson(res, 200, { ok: true, rules: payload });
  }

  if (req.method === "PUT" && reqUrl.pathname === "/api/admin/feed-edition") {
    const payload = await readJsonBody(req);
    const pages = payload?.pages;
    if (!Array.isArray(pages)) {
      return sendJson(res, 400, { error: "pages must be an array" });
    }
    const normalizedPages = pages.map((page) => {
      const tids = Array.isArray(page) ? page : page?.tids;
      return (Array.isArray(tids) ? tids : []).map(Number).filter(Number.isFinite);
    }).filter((page) => page.length);
    if (!normalizedPages.length) {
      return sendJson(res, 400, { error: "pages must contain at least one tid" });
    }

    const raw = await fs.readFile(rulesPath, "utf8");
    const rules = JSON.parse(raw);
    rules.feedEditions = {
      pageSize: Number(payload.pageSize || rules.feedEditions?.pageSize || 10),
      generatedAt: payload.generatedAt || new Date().toISOString(),
      strategy: payload.strategy || "daily-curated-batches",
      notes: Array.isArray(payload.notes) ? payload.notes : [],
      pages: normalizedPages
    };
    await writeJsonFile(rulesPath, rules);
    memory.rules = rules;
    memory.rulesLoadedAt = Date.now();
    memory.feedPages.clear();
    return sendJson(res, 200, { ok: true, feedEditions: rules.feedEditions });
  }

  if (req.method === "GET" && reqUrl.pathname === "/api/admin/post-metadata") {
    const raw = await fs.readFile(metadataPath, "utf8");
    return sendJson(res, 200, JSON.parse(raw));
  }

  if (req.method === "PUT" && reqUrl.pathname === "/api/admin/post-metadata") {
    const payload = await readJsonBody(req);
    if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
      return sendJson(res, 400, { error: "post metadata must be a JSON object" });
    }
    const data = payload.items ? payload : { items: payload };
    if (!data.items || typeof data.items !== "object" || Array.isArray(data.items)) {
      return sendJson(res, 400, { error: "items must be an object" });
    }
    await writeJsonFile(metadataPath, data);
    memory.metadata = data.items;
    memory.metadataLoadedAt = Date.now();
    memory.feedPages.clear();
    return sendJson(res, 200, { ok: true, metadata: data });
  }

  const metadataMatch = reqUrl.pathname.match(/^\/api\/admin\/post-metadata\/(\d+)$/);
  if ((req.method === "PATCH" || req.method === "DELETE") && metadataMatch) {
    const tid = metadataMatch[1];
    const raw = await fs.readFile(metadataPath, "utf8").catch(() => "{\"items\":{}}");
    const data = JSON.parse(raw);
    data.items ||= {};
    if (req.method === "DELETE") {
      delete data.items[tid];
    } else {
      const payload = await readJsonBody(req);
      if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
        return sendJson(res, 400, { error: "metadata patch must be a JSON object" });
      }
      data.items[tid] = { ...(data.items[tid] || {}), ...payload };
    }
    await writeJsonFile(metadataPath, data);
    memory.metadata = data.items;
    memory.metadataLoadedAt = Date.now();
    memory.feedPages.clear();
    return sendJson(res, 200, { ok: true, tid: Number(tid), item: data.items[tid] || null });
  }

  if (req.method === "POST" && reqUrl.pathname === "/api/admin/reload") {
    memory.feedPages.clear();
    memory.topicDetails.clear();
    memory.rules = null;
    memory.metadata = null;
    memory.snapshot = null;
    return sendJson(res, 200, { ok: true });
  }

  return sendJson(res, 404, { error: "admin route not found" });
}

async function handleApi(req, reqUrl, res) {
  try {
    if (req.method === "GET" && reqUrl.pathname === "/api/setup/status") {
      return sendJson(res, 200, {
        required: isSetupRequired(),
        configured: !isSetupRequired(),
        nodebbBaseUrl: config.nodebbBaseUrl,
        nodebbUid: config.nodebbUid,
        nodebbCid: config.nodebbCid,
        dataMode: config.dataMode,
        cloudinaryConfigured: Boolean(config.cloudinaryUrl)
      });
    }
    if (req.method === "POST" && reqUrl.pathname === "/api/setup") {
      const payload = await readJsonBody(req);
      await saveSetupConfig(payload);
      return sendJson(res, 200, { ok: true, configured: true });
    }
    if (reqUrl.pathname.startsWith("/api/admin/")) return await handleAdmin(req, reqUrl, res);
    if (isSetupRequired()) {
      return sendJson(res, 428, { error: "setup required" });
    }
    if (req.method === "GET" && reqUrl.pathname === "/api/feed") return await handleFeed(reqUrl, res);
    if (req.method === "GET" && reqUrl.pathname === "/api/snapshot/status") {
      try {
        const snapshot = await readSnapshot();
        return sendJson(res, 200, {
          exists: true,
          dataMode: config.dataMode,
          source: snapshot.source || "snapshot",
          generatedAt: snapshot.generatedAt || null,
          checkedAt: snapshot.checkedAt || null,
          topicCount: snapshot.topics?.length || 0,
          assetDir: "/snapshot-assets"
        });
      } catch {
        return sendJson(res, 200, { exists: false, dataMode: config.dataMode });
      }
    }
    if (req.method === "GET" && reqUrl.pathname === "/api/tags") return sendJson(res, 200, await nodebbFetch("/api/tags"));
    if (req.method === "GET" && reqUrl.pathname === "/api/map/items") {
      return sendJson(res, 200, {
        bounds: { southWest: { lat: 18.37305, lng: 109.99538 }, northEast: { lat: 18.413856, lng: 110.036262 } },
        items: mapItems
      });
    }
    if (req.method === "GET" && reqUrl.pathname === "/api/messages") return await handleMessages(res);
    if (req.method === "GET" && reqUrl.pathname === "/api/me") return await handleMe(res);
    if (req.method === "GET" && /^\/api\/posts\/\d+$/.test(reqUrl.pathname)) {
      const tid = Number(reqUrl.pathname.split("/").pop());
      return await handlePostDetail(tid, res);
    }
    if (req.method === "POST" && reqUrl.pathname === "/api/upload/image") return await handleUploadImage(req, res);
    if (req.method === "POST" && reqUrl.pathname === "/api/posts") return await handleCreatePost(req, res);
    sendJson(res, 404, { error: "not found" });
  } catch (error) {
    sendJson(res, error.status || 500, { error: error.message || "server error" });
  }
}

async function serveStatic(reqUrl, res) {
  let pathname = decodeURIComponent(reqUrl.pathname);
  if (pathname === "/") pathname = "/index.html";
  const filePath = path.normalize(path.join(publicDir, pathname));
  if (!filePath.startsWith(publicDir)) {
    sendText(res, 403, "Forbidden");
    return;
  }
  try {
    const data = await fs.readFile(filePath);
    const type = MIME[path.extname(filePath).toLowerCase()] || "application/octet-stream";
    res.writeHead(200, { "content-type": type, "cache-control": "no-cache" });
    res.end(data);
  } catch {
    const index = await fs.readFile(path.join(publicDir, "index.html"));
    res.writeHead(200, { "content-type": MIME[".html"], "cache-control": "no-cache" });
    res.end(index);
  }
}

const server = http.createServer(async (req, res) => {
  const reqUrl = new URL(req.url || "/", `http://${req.headers.host || "localhost"}`);
  if (reqUrl.pathname.startsWith("/api/")) {
    await handleApi(req, reqUrl, res);
    return;
  }
  if (isSetupRequired()) {
    sendText(res, 200, setupPageHtml(), "text/html; charset=utf-8");
    return;
  }
  await serveStatic(reqUrl, res);
});

server.listen(config.port, () => {
  console.log(`Lian mobile web running at http://localhost:${config.port}`);
});
